[workspace]
members = ["small-agent", "learn-adk-rust", "liter-llm-demo", "simple-rag"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.104"
async-openai = { version = "0.41.3", features = [
  "chat-completion",
  "byot",
  "embedding",
] }
dotenvy = "0.15.7"
futures-util = "0.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
