[package]
name = "learn-adk-rust"
version = "0.1.0"
edition = "2024"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adk-rust = { version = "2.0.0", features = ["deepseek"] }
anyhow = { workspace = true }
dotenvy = { workspace = true }
tokio = { workspace = true }
